# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poked', models.IntegerField(default='1')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='loginapp.Userlog')),
                ('userpoked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='loginapp.Userlog')),
            ],
        ),
    ]
